### PR TITLE
Fix url to 0.73-3.tar.gz and sha256

### PR DESCRIPTION
**Pull request by dounokouno**
Thank you for merging my PR in the csshx repository.

https://github.com/parera10/csshx/pull/3

The configuration of homebrew fomura has been modified accordingly. The sha256 value was calculated from a download from https://github.com/parera10/csshx/archive/master.tar.gz.

If you would like to merge this PR, please add the latest state of the [csshx repository](https://github.com/parera10/csshx) with the tag `0.73-3` and then merge.

Thank you.

### CODE REVIEW

**Review by parera10 — COMMENTED** [review]
I think that the hash is not correct. I get this one with shasum -a 256:
f17986100f7c469bde8bfe2073f02c7ffcf9dac1becb623e9e39d922d1f0874a

**Comment by parera10** [comment]
I've pushed version update directly on master. Clossig PR.

**Comment by dounokouno** [comment]
@parera10 

Thank you for your support on the master branch. I tried to install it with `brew`, but it said SHA256 is mismatched, so I'll send you a PR afterwards.

```
$ brew install parera10/csshx/csshx
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 2 formulae.

==> Installing csshx from parera10/csshx
==> Downloading https://github.com/parera10/csshx/archive/0.73-3.tar.gz
==> Downloading from https://codeload.github.com/parera10/csshx/tar.gz/0.73-3
 # #=O#-  #                                                                   
Error: SHA256 mismatch
Expected: f17986100f7c469bde8bfe2073f02c7ffcf9dac1becb623e9e39d922d1f0874a
  Actual: c12e7fa99be840987809faf873b96ad5bbc24802e1d9df82391242d30744b73a
    File: /Users/username/Library/Caches/Homebrew/downloads/d2ddb503d885b0a350c7827fbb0e26955d17296f8a630f91745f1aecb78eccf7--csshx-0.73-3.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by dounokouno** [comment]
@parera10

I have created a PR. Please check it out. #2

**Pull request closed without merging**
